import { existsSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { readJson, readText, removeFile, writeJson, writeText } from "../core/fsutil.mjs";

// OpenCode: TypeScript/JS plugins get an in-process `tool.execute.before`
// hook — the cleanest injection point of all hosts: we mutate the bash args
// directly, no wire-format guessing. The generated plugin imports the shared
// policy from the installed payload so the prefix list has one home.

function pluginFile(home) {
  return join(home, ".config", "opencode", "plugin", "scrooge-kit.js");
}

function opencodeConfig(home) {
  return join(home, ".config", "opencode", "opencode.json");
}

function pluginSource(payloadDir) {
  const policyUrl = pathToFileURL(join(payloadDir, "scripts", "lib", "policy.mjs")).href;
  return `// Generated by scrooge-kit — do not edit (re-run \`scrooge-kit install\` instead).
import { rewriteCommand } from ${JSON.stringify(policyUrl)};
import { execFileSync } from "node:child_process";

let rtkProbe = null;
function rtkAvailable() {
  if (rtkProbe !== null) return rtkProbe;
  try {
    execFileSync(process.platform === "win32" ? "where" : "which", ["rtk"], { stdio: "ignore", timeout: 2000 });
    rtkProbe = true;
  } catch {
    rtkProbe = false;
  }
  return rtkProbe;
}

export const ScroogeKit = async () => ({
  "tool.execute.before": async (input, output) => {
    try {
      if (input.tool !== "bash") return;
      const cmd = output.args?.command;
      if (!rtkAvailable()) return;
      const rewritten = rewriteCommand(cmd, process.env);
      if (rewritten) output.args.command = rewritten;
    } catch {
      // fail-open: never break the session over token savings
    }
  },
});
`;
}

export function install(ctx) {
  const { home, journal, payloadDir } = ctx;
  writeText(journal, pluginFile(home), pluginSource(payloadDir));
  if (ctx.headroomAvailable) {
    const file = opencodeConfig(home);
    const config = readJson(file, {});
    if (!config.mcp?.headroom) {
      writeJson(journal, file, {
        ...config,
        mcp: {
          ...(config.mcp ?? {}),
          headroom: { type: "local", command: ["headroom", "mcp", "serve"], enabled: true },
        },
      });
    }
  }
}

export function uninstall(ctx) {
  const { home, journal } = ctx;
  removeFile(journal, pluginFile(home));
  const file = opencodeConfig(home);
  const config = readJson(file);
  const entry = config?.mcp?.headroom;
  if (entry && JSON.stringify(entry) === JSON.stringify({ type: "local", command: ["headroom", "mcp", "serve"], enabled: true })) {
    delete config.mcp.headroom;
    if (Object.keys(config.mcp).length === 0) delete config.mcp;
    writeJson(journal, file, config);
  }
}

export function verify(ctx) {
  const file = pluginFile(ctx.home);
  return [
    { name: "plugin file present", pass: existsSync(file) },
    { name: "plugin mentions rewriteCommand", pass: readText(file).includes("rewriteCommand") },
  ];
}
